server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.80.168:9300
  rabbitmq:
    virtual-host: /yihuo
    username: yihuo
    password: yihuo
    host: 192.168.80.168
  jackson:
    default-property-inclusion: non_null # 配置json处理时忽略空值
  resources:
    add-mappings: true
    chain:
      enabled: true
      gzipped: true
      html-application-cache: true
    cache:
      period: 3600m
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
    lease-expiration-duration-in-seconds: 10 #10秒不发送九过期
    lease-renewal-interval-in-seconds: 5 #每隔5秒发一次心跳
ribbon:
 ConnectTimeout: 500000 #请求连接的超时时间，默认时间为1秒
 ReadTimeout: 500000 #请求处理的超时时间
