server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /yihuo
    username: yihuo
    password: yihuo
    host: 192.168.80.168

yihuo:
  sms:
    accessKeyId: LTAIc259TULYzaS7
    accessKeySecret: 1uh79I1UAmwQ4YWsSmOgxw7JEBGA0v
    signName: 易货
    verifyCodeTemplate: SMS_148614415
